#!/usr/bin/env bash
zip -r -u app.nw index.html package.json css/* font/* img/* js/* server/lib`getconf LONG_BIT` server/client/* server/server.js server/package.json server/node_modules/* server/apparmor/bin/apparmor`getconf LONG_BIT` server/config.js server/scripts/*
