#!/usr/bin/env bash
arch=`getconf LONG_BIT`
CURRENT_DIR=`readlink -f .`
export LD_LIBRARY_PATH=$CURRENT_DIR/nodewebkit/nodewebkit$arch:/lib:$LD_LIBRARY_PATH
./repack `getconf LONG_BIT`
./nodewebkit/nodewebkit$arch/nw app.nw
exit 0
