#!/usr/bin/env bash
arch=`getconf LONG_BIT`
CURRENT_DIR=`readlink -f .`
export LD_LIBRARY_PATH=$CURRENT_DIR/node_modules/nodewebkit/nodewebkit/:$LD_LIBRARY_PATH
./repack
./node_modules/nodewebkit/nodewebkit$arch/nw app.nw
exit 0
