#!/usr/bin/env bash
rsync -ra -v -e "sshpass -p genius ssh -l codemagnus -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete /var/www/focus/focus/client/ 192.168.1.40:/home/codemagnus/Desktop/focus
