#!/usr/bin/env bash
 sshpass -p useruser ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@10.0.4.192 "export DISPLAY=:0.0; echo useruser | sudo -S killall app.run"
 sshpass -p useruser ssh  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@10.0.4.192 "export DISPLAY=:0.0; echo useruser | sudo -S /home/user/Desktop/focus/out32/run"


