#!/usr/bin/env bash
echo $LD_LIBRARY_PATH
if [ $# -eq 2 ]; then
    PORT=$2
    PASSWD=$1
    killall linux-app-arm
    kill $(ps aux | grep apparmor`getconf LONG_BIT` | awk '{print $2}')
    kill $(ps aux | grep sockify | grep python | awk '{print $2}')
    `readlink -f .`/server/client/utils/websockify --web `readlink -f .`/server/client 6080 localhost:$2 &
    `readlink -f .`/server/apparmor/bin/apparmor`getconf LONG_BIT` -nap -wait 50 -passwd "$1" -ncache -forever -rfbport $2 &
else
    echo "Error running vnc."
fi
